"""AI-native capability manifest for Zab surfaces.

This module is the source of truth for which features exist across Core, CLI,
MCP, API and UI. Keep it side-effect free so agents can call it for discovery.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

SURFACES = ("core", "cli", "mcp", "api", "ui")


def _capability(
    *,
    id: str,
    domain: str,
    summary: str,
    risk: str,
    core: str | None,
    cli: str | None,
    mcp: str | None,
    api: str | None,
    ui: str | None,
    status: str,
    parity_notes: str | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "id": id,
        "domain": domain,
        "summary": summary,
        "risk": risk,
        "core": core,
        "cli": cli,
        "mcp": mcp,
        "api": api,
        "ui": ui,
        "status": status,
    }
    if parity_notes:
        payload["parity_notes"] = parity_notes
    return payload


def get_capabilities() -> dict[str, Any]:
    """Return Zab's machine-readable Core/CLI/MCP/API/UI capability manifest."""

    capabilities = [
        _capability(
            id="capabilities.manifest",
            domain="meta",
            summary="Expose the AI-native surface parity manifest.",
            risk="read",
            core="zab.services.capabilities.get_capabilities",
            cli="zab capabilities --json",
            mcp="capabilities",
            api="GET /api/capabilities",
            ui="Capabilities",
            status="complete",
        ),
        _capability(
            id="agent.bootstrap",
            domain="agent",
            summary="Return the recommended bootstrap contract for coding agents.",
            risk="read",
            core="zab.services.agent_context.agent_bootstrap",
            cli="zab agent bootstrap --json",
            mcp="agent_bootstrap",
            api="GET /api/agent/bootstrap",
            ui="Capabilities / Agent contract",
            status="complete",
        ),
        _capability(
            id="source.health",
            domain="system",
            summary="Report source availability, auth readiness, freshness and safe repair hints.",
            risk="read",
            core="zab.services.source_health.get_source_health",
            cli="zab source-health --json",
            mcp="source_health",
            api="GET /api/source-health",
            ui="Source Health",
            status="complete",
        ),
        _capability(
            id="command_center.context_packet",
            domain="command_center",
            summary="Build the daily context-intelligence packet consumed by Hermes Command Center.",
            risk="read",
            core="zab.services.command_center_context.build_context_packet",
            cli="zab command-center context --json",
            mcp=None,
            api="GET /api/command-center/context",
            ui=None,
            status="partial",
            parity_notes="Core/CLI/API are implemented; Hermes consumes the generated files. Dedicated MCP/UI parity can follow after the packet proves useful in daily briefings.",
        ),
        _capability(
            id="research.packet",
            domain="research",
            summary="Build a deterministic, cited, freshness-aware context packet for humans and agents.",
            risk="read",
            core="zab.services.research_engine.research",
            cli="zab research <query> --json",
            mcp="research",
            api="POST /api/research",
            ui="Research",
            status="complete",
        ),
        _capability(
            id="search.global",
            domain="search",
            summary="Search the local Zab index across skills, projects, connectors, models and memory-source metadata.",
            risk="read",
            core="zab.services.agent_context.search",
            cli="zab search <query> --json",
            mcp="search",
            api="GET /api/search?q=<query>",
            ui="Capabilities / Search contract",
            status="partial",
            parity_notes="UI global search is not yet implemented; current UI links to the contract and existing resource views.",
        ),
        _capability(
            id="inspect.item",
            domain="inventory",
            summary="Inspect one indexed item after search or inventory listing.",
            risk="read",
            core="zab.services.state_index.get_section_item",
            cli="zab inspect <section> <key> --json",
            mcp="inspect",
            api="GET /api/inspect/{section}/{key}",
            ui="Capabilities / Inventory contract",
            status="partial",
            parity_notes="Generic REST inspect is available; dedicated dashboard detail parity is still planned.",
        ),
        _capability(
            id="tools.catalog",
            domain="tools",
            summary="Discover actionable tools, inspect their primary/fallback implementations and validate annotations.",
            risk="read",
            core="zab.services.tool_catalog.build_tools_catalog",
            cli="zab tools list --json",
            mcp=None,
            api="GET /api/tools/catalog",
            ui="Tools Catalog",
            status="partial",
            parity_notes="Core/CLI/API expose the catalog; a dedicated MCP surface is optional and can be added later if needed.",
        ),
        _capability(
            id="skills.manifest",
            domain="skills",
            summary="List compact skill activation records for agents.",
            risk="read",
            core="zab.services.agent_context.skills_manifest",
            cli="zab agent skills --json",
            mcp="skills_manifest",
            api="GET /api/agent/skills",
            ui="Skills",
            status="complete",
        ),
        _capability(
            id="tasks.list",
            domain="tasks",
            summary="List the unified task inbox from the local task cache.",
            risk="read",
            core="zab.services.tasks_inbox.fetch_tasks_inbox",
            cli="zab tasks list",
            mcp="tasks_list",
            api="GET /api/tasks/inbox",
            ui="Tasks Inbox",
            status="complete",
        ),
        _capability(
            id="tasks.sync",
            domain="tasks",
            summary="Refresh task cache from configured PM backends.",
            risk="external_read",
            core="zab.services.tasks_inbox.sync_tasks_inbox",
            cli="zab tasks sync",
            mcp="tasks_sync",
            api="POST /api/tasks/inbox/sync",
            ui="Tasks Inbox",
            status="complete",
        ),
        _capability(
            id="memory.search",
            domain="memory",
            summary="Search unified Postgres memory when configured.",
            risk="read",
            core="zab.services.memory_db.search_memory",
            cli="zab memory search <query>",
            mcp="memory_search",
            api="GET /api/memory/search?q=<query>",
            ui="Memory / Conversations",
            status="complete",
        ),
        _capability(
            id="security.status",
            domain="security",
            summary="Report secret presence and paths without returning raw secret values.",
            risk="read",
            core="zab.services.agent_context.security_status",
            cli="zab security status --json",
            mcp="security_status",
            api="GET /api/security/status",
            ui="Security",
            status="complete",
        ),
        _capability(
            id="system.check",
            domain="system",
            summary="Run the dashboard/system health check and stream check results.",
            risk="read",
            core="zab.services.system_check.run_system_check",
            cli="zab doctor",
            mcp="system_health_check",
            api="GET /api/system/check",
            ui="Check system",
            status="partial",
            parity_notes="MCP can run the aggregate check; JSON CLI parity for `zab doctor` is still separate.",
        ),
        _capability(
            id="cli.auth_check",
            domain="system",
            summary="Validate local CLI authentications from a declarative JSON check file.",
            risk="external_read",
            core="zab.services.cli_check.run_cli_checks",
            cli="zab cli-check --json",
            mcp="cli_auth_check",
            api="GET /api/cli-check",
            ui="CLI auth",
            status="complete",
        ),
        _capability(
            id="connectors.list",
            domain="connectors",
            summary="List agent-actionable connectors from MCP, local API proxies and Composio accounts.",
            risk="read",
            core="zab.services.agent_context.connectors_list",
            cli="zab inventory connectors --json",
            mcp="connectors_list",
            api="GET /api/connectors",
            ui="Connectors",
            status="complete",
        ),
        _capability(
            id="connectors.status",
            domain="connectors",
            summary="Inspect one connector and run read-only availability checks.",
            risk="external_read",
            core="zab.services.agent_context.connector_status",
            cli="zab inspect connectors <slug> --json",
            mcp="connector_status",
            api="GET /api/connectors/{slug}/check",
            ui="Connectors / Check",
            status="complete",
        ),
        _capability(
            id="composio.connections",
            domain="connectors",
            summary="List Composio connected accounts, optionally resolving account identity without returning secrets.",
            risk="external_read",
            core="zab.services.agent_context.composio_connections",
            cli="zab composio connections --json",
            mcp="composio_connections",
            api="GET /api/composio/connections",
            ui="Connectors",
            status="complete",
        ),
        _capability(
            id="tasks.sources_status",
            domain="tasks",
            summary="List configured task sources with cache status and masked token presence.",
            risk="read",
            core="zab.services.agent_context.task_sources_status",
            cli="zab config --json",
            mcp="task_sources_status",
            api="GET /api/tasks/secret-locations",
            ui="Tasks Inbox",
            status="partial",
            parity_notes="MCP returns the most compact agent contract; API/UI split this across inbox, secret locations and config views.",
        ),
        _capability(
            id="tasks.source_check",
            domain="tasks",
            summary="Check one configured task source and update its local cache block.",
            risk="external_read",
            core="zab.services.agent_context.task_source_check",
            cli="zab cli-check --json",
            mcp="task_source_check",
            api="POST /api/tasks/sources/{source_id}/check",
            ui="Tasks Inbox",
            status="partial",
            parity_notes="Dedicated human CLI command is not separate yet; API/MCP expose the precise source check.",
        ),
        _capability(
            id="channels.list",
            domain="channels",
            summary="List communication channels and cached action items; refresh can read external channels explicitly.",
            risk="external_read",
            core="zab.services.agent_context.channels_list",
            cli="zab channels list",
            mcp="channels_list",
            api="GET /api/channels",
            ui="Channels / Cockpit",
            status="complete",
        ),
        _capability(
            id="project.handoff",
            domain="agent",
            summary="Compose project-specific context pack and routing hints for an agent.",
            risk="read",
            core="zab.services.agent_context.project_handoff",
            cli="zab agent handoff --project <project> --json",
            mcp="project_handoff",
            api="POST /api/agent/handoff",
            ui="Projects",
            status="complete",
        ),
    ]

    summary = {
        "total": len(capabilities),
        "complete": sum(1 for cap in capabilities if cap["status"] == "complete"),
        "partial": sum(1 for cap in capabilities if cap["status"] == "partial"),
        "deferred": sum(1 for cap in capabilities if cap["status"] == "deferred"),
        "missing": sum(1 for cap in capabilities if cap["status"] == "missing"),
    }

    return {
        "contract": "capability-manifest",
        "contract_version": "1.0",
        "name": "zab",
        "description": "AI-native workspace orchestrator exposing capabilities across Core, CLI, MCP, API and UI.",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "contracts": {
            "json_cli": True,
            "non_interactive_cli": True,
            "mcp_tools": True,
            "http_api": True,
            "ui_dashboard": True,
            "head_smoke": True,
            "core_service_boundary": True,
        },
        "surfaces": list(SURFACES),
        "capabilities": capabilities,
        "summary": summary,
        **summary,
    }
