#!/usr/bin/env bash
# Install a shell wrapper for zab (clone + uv) or use an existing pip/pipx install.
#
# Usage:
#   ./scripts/install-zab-shell.sh [PATH_TO_ZAB_REPO]
#
# If `zab` is already on PATH (pip/pipx install), this script only ensures
# ~/.config/zab/config.yaml exists and prints usage hints.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${1:-$SCRIPT_DIR/..}"
REPO="$(cd "$REPO" && pwd)"
LOADER="$HOME/.zab-shell.sh"
MARKER="# zab-loader (source ~/.zab-shell.sh)"

if command -v zab >/dev/null 2>&1 && ! declare -F zab >/dev/null 2>&1; then
  FOUND_ZAB="$(command -v zab)"
  if zab --help >/dev/null 2>&1; then
    echo "Found working pip/pipx/uv-tool zab on PATH: $FOUND_ZAB"
    echo "No shell wrapper needed. Configure ~/.config/zab/config.yaml (see config.example.yaml)."
    (
      cd "$REPO"
      uv run python -c "from zab.user_config import ensure_user_config_exists; p = ensure_user_config_exists(); print('  Config:', p) if p else print('  Config already present')"
    )
    exit 0
  fi

  echo "Found zab on PATH but it failed a smoke test: $FOUND_ZAB" >&2
  echo "Installing the shell wrapper so this checkout remains usable." >&2
fi

cat >"$LOADER" <<EOF
# Generated by scripts/install-zab-shell.sh — do not commit
export ZAB_REPO="$REPO"
# Fixed skills root (optional):
# export ZAB_SKILLS_ROOT=\$HOME/skills
zab() {
  local _zab_from="\$PWD"
  (cd "\$ZAB_REPO" && env ZAB_INVOCATION_CWD="\$_zab_from" uv run zab "\$@")
}
EOF
chmod 600 "$LOADER" 2>/dev/null || true
echo "Wrote: $LOADER"

append_source() {
  local rcfile="$1"
  [[ -f "$rcfile" ]] || touch "$rcfile"
  if grep -qF "$MARKER" "$rcfile" 2>/dev/null; then
    echo "Déjà référencé : $rcfile"
    return 0
  fi
  {
    echo ""
    echo "$MARKER"
    echo '[ -f "$HOME/.zab-shell.sh" ] && . "$HOME/.zab-shell.sh"'
  } >>"$rcfile"
  echo "Mis à jour : $rcfile"
}

append_source "$HOME/.bashrc"
append_source "$HOME/.bash_profile"
append_source "$HOME/.zshrc"

echo ""
echo "Configuration utilisateur (~/.config/zab/config.yaml)…"
(
  cd "$REPO"
  uv run python -c "from zab.user_config import ensure_user_config_exists; p = ensure_user_config_exists(); print('  Créé :', p) if p else print('  Déjà présent : ~/.config/zab/config.yaml')"
)

echo ""
echo "Nouveau terminal (ou : source ~/.bash_profile  /  source ~/.zshrc) : zab doctor"
echo "Immédiat dans ce terminal : source \"\$HOME/.zab-shell.sh\""
echo "Scripts non-interactifs : source \"\$HOME/.zab-shell.sh\" && zab doctor"
echo "Si la commande zab d'un autre .venv apparaît avant cette fonction : désinstalle-la (pip uninstall zab) ou vérifie votre PATH."
echo "Optionnel : export ZAB_SKILLS_ROOT=/chemin/fixe pour forcer la racine skills."
